version: '3.9'
services:
  web:
    image: php:8.2-apache
    ports: ["8080:80"]
    volumes: [".:/var/www/html"]
    depends_on: [db]
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: travel
      MYSQL_USER: travel_user
      MYSQL_PASSWORD: password
    ports: ["3306:3306"]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: ["8081:80"]
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
